### ISSUE TITLE
does not work at all in sublime text 3083

### ISSUE THREAD

**Issue by thecotne** [fitnr/SublimeDataConverter#16]
```
DataConverter had trouble sniffing: Could not determine delimiter
DataConverter: Using the default delimiter: ","
DataConverter: You can change the default delimiter in the settings file.
DataConverter: using dialect excel
DataConverter: CSV module had trouble sniffing for headers. Assuming they exist.
DataConverter: Set 'headers = false' in the settings to disable.
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 550, in run_
    return self.run(edit, **args)
  File "DataConverter in C:\Users\cotne\AppData\Roaming\Sublime Text 3\Installed Packages\DataConverter.sublime-package", line 105, in run
  File "DataConverter in C:\Users\cotne\AppData\Roaming\Sublime Text 3\Installed Packages\DataConverter.sublime-package", line 293, in import_csv
  File "DataConverter in C:\Users\cotne\AppData\Roaming\Sublime Text 3\Installed Packages\DataConverter.sublime-package", line 55, in parse
  File "DataConverter in C:\Users\cotne\AppData\Roaming\Sublime Text 3\Installed Packages\DataConverter.sublime-package", line 31, in get_type
TypeError: int() argument must be a string or a number, not 'NoneType'
```

**Comment by fitnr** [comment]
What's the CSV you're trying to convert?

**Comment by thecotne** [comment]
```
Serial	Name	Gender	Organization	Function	Nationality	ID number	Event	Photo
1	ALBERTAS MACIULEVICIUS	Male	National Olympic Committee of Lithuania	Athlete	Lithuania	22716289	Artistic Gymnastics	Have
2	IVETA DAUJOTAITE	Female	National Olympic Committee of Lithuania	Athlete	Lithuania	22939550	Tennis	Have
3	GABIJA ZAVACKYTE	Female	National Olympic Committee of Lithuania	Athlete	Lithuania	23576796	Swimming	Have
4	ALEKS MOLODECKIJ	Male	National Olympic Committee of Lithuania	Athlete	Lithuania	23786243	Judo	Have
5	MATAS GRUZAUSKAS	Male	National Olympic Committee of Lithuania	Athlete	Lithuania	23893639	Judo	Have
6	SELMA STEFANIA CADAR	Female	Romanian Olympic and Sports Committee	Athlete	Romania	052699767	Tennis	Have
7	ELENA STEFANIA MADALINA MITREA	Female	Romanian Olympic and Sports Committee	Athlete	Romania	052972079	Athletics	Have
8	MARKO JOVICIC	Male	Croatian Olympic Committee	Athlete	Croatia	117753658	Artistic Gymnastics	Have
9	JONATHAN HAVNDRUP SOERENSEN	Male	National Olympic Committee and Sports Confederation of Denmark	Athlete	Denmark	208270233	Handball	Have
10	ELENA EREMINA	Female	Russian Olympic Committee	Athlete	Russian Federation	717657111	Artistic Gymnastics	Have
11	ANASTASIIA KUTERINA	Female	Russian Olympic Committee	Athlete	Russian Federation	750764612	Judo	Have
12	MUHAMMED SELCUK	Male	Turkish Olympic Committee	Athlete	Turkey	13424615286	Cycling	Have
13	SENA BASAR	Female	Turkish Olympic Committee	Athlete	Turkey	49084900790	Cycling	Have
14	ARTUR JANIYEU	Male	National Olympic Committee of the Republic of Belarus	Athlete	Belarus	AB2778345	Judo	Have
15	ANSTASIJA ADZIC	Female	Montenegrin Olympic Committee	Athlete	Montenegro	B46DS8262	Handball	Have
16	MARINE LE BERRIGAUD	Female	The Olympic Committee of Monaco	Athlete	Monaco	F103682	Swimming	Have
17	YARASLAU KHILMANOVICH	Male	National Olympic Committee of the Republic of Belarus	Athlete	Belarus	KH2292043	Cycling	Have
18	KRISTINE STRAZDITE	Female	Latvian Olympic Committee	Athlete	Latvia	LV4170081	Athletics	Have
19	PATRICIJA KARLINA ROSHOFA	Female	Latvian Olympic Committee	Athlete	Latvia	LV4192453	Athletics	Have
20	MIRJANA MARKOVIC	Female	Montenegrin Olympic Committee	Athlete	Montenegro	R52LZ3600	Handball	Have

```

this is coped from excel 2013 i think it's valid csv

**Comment by fitnr** [comment]
HTML automatically converts the tabs in your snippet to spaces. When I converted back to tabs, I didn't have an issue.

I've pushed a release that addresses the area around the issue you saw. Can you install that (when it's available) and try again?

**Comment by thecotne** [comment]
issue still exists

https://gist.github.com/thecotne/81d1f56eb9b85a2771e4

(i created gist to keep tabs)


```
DataConverter: using sniffed dialect with delimiter: [tab character]
DataConverter: using dialect sniffed
DataConverter: CSV Sniffer found headers
```

**Comment by fitnr** [comment]
I can't reproduce this on OS X, and I don't have a WIndows machine handy at the moment. Are you selecting any part of the file when you run the command?

**Comment by thecotne** [comment]
i have tried with and without selecting text both ways it does not work

i will try to fix this when i get home


BTW it's good practice to add labels to issues 
so this issue should have bug and windows label
